# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]

    steps:
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    
    - name: Cache test dependencies
      uses: actions/cache@v2.1.5
      with:
        path: "~/.m2"
        key: "test-cache-${{ matrix.java }}"
        
    - name: Clone
      uses: actions/checkout@v2.3.4
      
    - name: Test
      run: mvn test --batch-mode --no-snapshot-updates

  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]

    steps:
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    
    - name: Cache build dependencies
      uses: actions/cache@v2.1.5
      with:
        path: "~/.m2"
        key: "build-cache-${{ matrix.java }}"
        
    - name: Clone
      uses: actions/checkout@v2.3.4
      
    - name: Package
      run: mvn package --batch-mode -DskipTests --file pom.xml
      
    - name: Uplod as artifact
      uses: actions/upload-artifact@v2
      with:
        name: maven-build-scanner-${{ matrix.java }}
        path: /home/runner/work/maven-build-scanner/maven-build-scanner/target/maven-build-scanner-1.0.0-SNAPSHOT-jar-with-dependencies.jar
