# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Download dependencies
      run: mvn --batch-mode dependency:resolve-plugins dependency:resolve 
        
    - name: Compile
      run: mvn compile --batch-mode
  
    - name: Test
      run: mvn test --batch-mode
      
    - name: Build with Maven
      run: mvn package --batch-mode -DskipTests --file pom.xml
      
    - uses: actions/upload-artifact@v2
      with:
        name: maven-build-scanner
        path: /home/runner/work/maven-build-scanner/maven-build-scanner/target/maven-build-scanner-1.0.0-SNAPSHOT-jar-with-dependencies.jar
